# Generated by Django 3.2 on 2022-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_reviews', '0006_alter_productreview_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
    ]
