# Generated by Django 3.2 on 2022-01-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
