# Generated by Django 3.2 on 2022-01-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220117_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='products.product'),
        ),
    ]
