# Generated by Django 3.2 on 2022-01-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariations_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
    ]
