# Generated by Django 3.2 on 2022-01-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_rating'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='name',
        ),
    ]
