# Generated by Django 3.2 on 2022-02-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_order_with_respect_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_variations',
        ),
    ]
