# Generated by Django 3.2 on 2022-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_has_sizes_product_has_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_variations',
            field=models.BooleanField(default=False),
        ),
    ]
