# Generated by Django 3.2 on 2022-02-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_has_variations'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to=None,
        ),
    ]
