# Generated by Django 3.2 on 2022-02-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to=None,
        ),
    ]
