# Generated by Django 3.2 on 2022-02-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to=None,
        ),
    ]
